repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use the latest stable version
    hooks:
      - id: black
        args: ["--line-length=100"]  # Set max line length if needed

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1  # Latest available version
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # General useful hooks
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta  # Dockerfile linting
    hooks:
      - id: hadolint
